# Generated by Django 5.0.6 on 2024-06-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_alter_tickets_attendee_alter_tickets_booking_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering_detail', models.CharField(default='', max_length=300)),
                ('cost', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.events')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_detail', models.CharField(default='', max_length=300)),
                ('cost', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.events')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_detail', models.CharField(default='', max_length=300)),
                ('cost', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.events')),
                ('vendor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vendors')),
            ],
        ),
    ]
