# Generated by Django 5.0.6 on 2024-06-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catering',
            options={'verbose_name_plural': 'Catering'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='transportation',
            options={'verbose_name_plural': 'Transportation'},
        ),
    ]
