# Generated by Django 5.0.6 on 2024-06-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tickets_attendee_alter_tickets_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.attendees'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='booking_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.reservation'),
        ),
    ]
