# Generated by Django 5.0.6 on 2024-06-28 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tickets_attendee_alter_tickets_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='organizer_name',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Event Vendors'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
