# Generated by Django 5.0.6 on 2024-06-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_payment_options_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
