# Generated by Django 5.0.6 on 2024-06-28 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_payment_options_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='email',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Attendees'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
