# Generated by Django 5.0.6 on 2024-06-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_attendees_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
