# Generated by Django 5.0.6 on 2024-06-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_tickets_payment_status_tickets_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='booking_name',
        ),
    ]
