# Generated by Django 5.0.6 on 2024-06-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_tickets_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='cost',
        ),
        migrations.AddField(
            model_name='events',
            name='venue_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
