# Generated by Django 5.0.6 on 2024-06-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_events_end_date_remove_events_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
