# Generated by Django 5.0.6 on 2024-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_events_end_time_events_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Food_cost_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
