# Generated by Django 5.0.6 on 2024-06-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_events_food_cost_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Food_cost_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
