# Generated by Django 5.0.6 on 2024-06-30 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_events_food_cost_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='base.events'),
        ),
    ]
