# Generated by Django 5.0.6 on 2024-06-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_attendees_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='payment_amount',
        ),
    ]
