# Generated by Django 5.0.6 on 2024-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_tickets_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
