# Generated by Django 5.0.6 on 2024-07-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_tickets_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='base.attendees'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='base.events'),
        ),
    ]
