# Generated by Django 5.0.6 on 2024-07-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_tickets_attendee_alter_tickets_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='ticket_no',
        ),
    ]
