# Generated by Django 5.0.6 on 2024-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_tickets_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tickets',
            name='khalti_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tickets',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tickets',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
