# Generated by Django 5.0.6 on 2024-07-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_tickets_payment_amount_tickets_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='payment_method',
        ),
    ]
