# Generated by Django 5.0.6 on 2024-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_tickets_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
